version: "3.2"
services:

  mongodb:
    image: 'mongo:4.2.10-bionic'
    container_name: geo-service-mongo-container
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: testdb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-dumps:/var/mongo-dumps
      - "$PWD/config/mongo/:/docker-entrypoint-initdb.d/"
    command: mongod
